# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 118a5d3821874f101b77a805756f11323588c9faa1b4dc7c8d44f1748c495448aab65686da7a4aabfd330172f289e030898ff0c07070a3a20a3a78775cc92ac8

test:
  secret_key_base: 33db0a83f988a8a5611cac438abafe20ddefe3b897a0f15fd0fe0aeeda51ba626eb58dca80944272609286af6cc48cd709ed19697bd83333e53ae99b1823f462

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
